Pronoun Roles
NinoMaruszewski/roycemorebot pull request #22
Opened 2021-02-02 18:58 UTC by NinoMaruszewski

Closes #21

2021-02-02 21:44 UTC, AlemSnyder commented on roycemorebot/exts/pronouns.py
> +        # User is switching roles, remove all current roles
no only toggle

2021-02-02 21:45 UTC, AlemSnyder commented on roycemorebot/exts/pronouns.py
> +                await ctx.author.remove_roles(
why not `try remove(he-him role)`

2021-02-02 21:46 UTC, AlemSnyder requested changes
people should be able to have multiple pronoun roles

2021-02-02 22:03 UTC, NinoMaruszewski commented on roycemorebot/exts/pronouns.py
> +                await ctx.author.remove_roles(
You don't need the `try`.

2021-02-03 16:01 UTC, AlemSnyder approved these changes

2021-02-03 16:01 UTC, merged